version: '3.0'
services:
  orca:
    image: pcic/orca:2.0.0
    container_name: orca
    ports:
      - "30333:5000"

    tmpfs:
      - /tmp:size=5G

networks:
  default:
    external:
      name: pcicbr0
