services:
  orca:
    image: pcic/orca:i34-metadata-requests
    container_name: orca
    environment:
        - TMPDIR=/scratch
    ports:
      - "30333:5000"
    tmpfs:
      - /tmp:size=5G
    volumes:
      - /scratch:/scratch

networks:
  default:
    external:
      name: pcicbr0
