name: Black

on: push

jobs:
  black:

    runs-on: ubuntu-24.04
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          options: ". --check"
          version: "25.9.0"
